function [approach_direction,id,is_varying,max_prefix,max_visible,metar_reports_id,min_prefix,min_visible,runway] = metarrunwaygroups(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [APPROACH_DIRECTION,ID,IS_VARYING,MAX_PREFIX,MAX_VISIBLE,METAR_REPORTS_ID,MIN_PREFIX,MIN_VISIBLE,RUNWAY]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [APPROACH_DIRECTION,ID,IS_VARYING,MAX_PREFIX,MAX_VISIBLE,METAR_REPORTS_ID,MIN_PREFIX,MIN_VISIBLE,RUNWAY]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [approach_direction,id,is_varying,max_prefix,max_visible,metar_reports_id,min_prefix,min_visible,runway]
%   = importfile('metarrunwaygroups.csv',2, 3814);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2013/09/19 22:39:07

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
%	column6: double (%f)
%   column7: text (%s)
%	column8: text (%s)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%s%s%f%f%s%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
approach_direction = dataArray{:, 1};
id = dataArray{:, 2};
is_varying = dataArray{:, 3};
max_prefix = dataArray{:, 4};
max_visible = dataArray{:, 5};
metar_reports_id = dataArray{:, 6};
min_prefix = dataArray{:, 7};
min_visible = dataArray{:, 8};
runway = dataArray{:, 9};

